openapi: 3.0.1
info:
  title: Elevator Management Platform
  description: central elevator management platform running in the cloud. This platform
    will operate the button pressed on the inside and outside of the elevator of a
    given hotel.
  contact:
    email: pradeeepsharma@gmail.com
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
- url: https://emp.swagger.io/emp
- url: http://emp.swagger.io/emp
tags:
- name: hotels
  description: All hotels available in chain
- name: elevators
  description: Management of elevators
- name: movement
  description: Travel record of an elevator
paths:
  /hotels/{id}:
    get:
      tags:
      - hotels
      summary: List all hotels in chain
      description: With Id it will return only one hotlel with details
      operationId: getHotels
      parameters:
      - name: id
        in: path
        description: ID of hotel to see the details
        required: false
        schema:
          type: integer
          format: int64
      responses:
        200:
          description: successful operation
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/Hotel'
            application/json:
              schema:
                $ref: '#/components/schemas/Hotel'
        400:
          description: Invalid ID supplied
          content: {}
        404:
          description: Hotel not found
          content: {}
  /hotels/{id}/elevators:
    get:
      tags:
      - hotels
      summary: List of elevators in the hotel
      operationId: getElevatorsInHotel
      parameters:
      - name: id
        in: path
        description: ID of hotel in which elevators are being searched
        required: true
        schema:
          type: integer
          format: int64
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Hotel'
        400:
          description: Invalid ID supplied
          content: {}
        404:
          description: Hotel not found
          content: {}
  /elevators/{id}:
    get:
      tags:
      - elevators
      summary: Returns elevators in hotel specified by id
      operationId: getElevators
      parameters:
      - name: id
        in: path
        description: ID of hotel in which elevators are searched
        required: true
        schema:
          type: integer
          format: int64
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Hotel'
        400:
          description: Invalid ID supplied
          content: {}
        404:
          description: Hotel not found
          content: {}
  /store/order:
    post:
      tags:
      - store
      summary: Place an order for a pet
      operationId: placeOrder
      requestBody:
        description: order placed for purchasing the pet
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/Order'
        required: true
      responses:
        200:
          description: successful operation
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/Order'
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
        400:
          description: Invalid Order
          content: {}
      x-codegen-request-body-name: body
  /store/order/{orderId}:
    get:
      tags:
      - store
      summary: Find purchase order by ID
      description: For valid response try integer IDs with value >= 1 and <= 10.         Other
        values will generated exceptions
      operationId: getOrderById
      parameters:
      - name: orderId
        in: path
        description: ID of pet that needs to be fetched
        required: true
        schema:
          maximum: 10.0
          minimum: 1.0
          type: integer
          format: int64
      responses:
        200:
          description: successful operation
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/Order'
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
        400:
          description: Invalid ID supplied
          content: {}
        404:
          description: Order not found
          content: {}
    delete:
      tags:
      - store
      summary: Delete purchase order by ID
      description: For valid response try integer IDs with positive integer value.         Negative
        or non-integer values will generate API errors
      operationId: deleteOrder
      parameters:
      - name: orderId
        in: path
        description: ID of the order that needs to be deleted
        required: true
        schema:
          minimum: 1.0
          type: integer
          format: int64
      responses:
        400:
          description: Invalid ID supplied
          content: {}
        404:
          description: Order not found
          content: {}
components:
  schemas:
    Hotel:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        floors:
          type: integer
          format: int32
        address:
          type: string
          format: date-time
        elevators:
          type: array
          items:
            $ref: '#/components/schemas/Dummy'
      xml:
        name: Hotel
    Elevator:
      type: object
      properties:
        id:
          type: integer
          format: int64
        hotelId:
          type: integer
          format: int64
        restricted:
          type: boolean
          default: false
        status:
          type: string
          enum:
          - active
          - broken
          - inactive
      xml:
        name: Elevator
    Travel:
      type: object
      properties:
        elevatorId:
          type: integer
          format: int64
        hotelId:
          type: integer
          format: int64
        date:
          type: string
          format: date/time
        triggerd:
          type: string
          enum:
          - inside
          - outside
        startFloor:
          type: integer
          format: int3
        stopFloor:
          type: integer
          format: int3
      xml:
        name: Travel
    Dummy:
      type: object
      properties:
        name:
          type: string
    ApiResponse:
      type: object
      properties:
        code:
          type: integer
          format: int32
        type:
          type: string
        message:
          type: string
