application:
  name: emp-hotel-api
server:
  port: 8080
spring:
  datasource:
    initialize: true
  #  data: classpath:data.sql
    url: jdbc:mysql://localhost:3306/emp_db
    username: root
    password: password
    driver-calss-name: com.mysql.jdbc.Driver
  jpa:

    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate.ddl-auto: update