application:
  name: emp-hotel-api
server:
  port: 8081
spring:
  datasource:
    initialize: true
 #   driverClassName: org.h2.Driver
    data: classpath:data.sql
    url: jdbc:h2:mem:EMP_DB
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true
    console.path: /h2-ui
