application:
  name: emp-hotel-api
server:
  port: 8080
spring:
  datasource:
    initialize: true
    data: classpath:data.sql
  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
