spring:
  datasource:
    initialize: true
  #  data: classpath:data.sql
    url: jdbc:mysql://localhost:3306/emp_db
    username: root
    password: password
    #driverClassName: com.mysql.jdbc.Driver
  jpa:
    defer-datasource-initialization: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate.ddl-auto: update